-- Seed podcast sources into Supabase
-- Run once after schema.sql to populate initial sources

INSERT INTO sources (id, name, url, source_type, domain, enabled, deleted, created_at)
VALUES
  ('c442f6ffcc34', 'Test: AI Short Talk',    'https://www.youtube.com/watch?v=zjkBMFhNj_g',                                                                                                                                        'youtube', 'Technology & AI',          true, false, NOW()),
  ('f05479133207', 'Huberman Lab',            'https://feeds.megaphone.fm/hubermanlab',                                                                                                                                             'rss',     'Health & Science',           true, false, NOW()),
  ('d278ef8e79f6', 'All-In Podcast',          'https://feeds.megaphone.fm/all-in-with-chamath-palihapitiya',                                                                                                                        'rss',     'Business & Startups',        true, false, NOW()),
  ('89f8c731675a', 'My First Million',        'https://feeds.megaphone.fm/my-first-million',                                                                                                                                        'rss',     'Business & Startups',        true, false, NOW()),
  ('c6244d59cb62', 'The Tim Ferriss Show',    'https://rss.art19.com/tim-ferriss-show',                                                                                                                                             'rss',     'Leadership & Productivity',  true, false, NOW()),
  ('ad094143a2cf', 'Planet Money',            'https://feeds.npr.org/510289/podcast.xml',                                                                                                                                           'rss',     'Finance & Investing',         true, false, NOW()),
  ('8aa4e90258d1', 'Hidden Brain',            'https://feeds.npr.org/510308/podcast.xml',                                                                                                                                           'rss',     'Society & Culture',           true, false, NOW()),
  ('3ff067cec93d', 'Lex Fridman Podcast',     'https://lexfridman.com/feed/podcast/',                                                                                                                                               'rss',     'Technology & AI',             true, false, NOW()),
  ('9d4f26dce0a7', 'Daily Tech News Show',    'https://dailytechnewsshow.com/feed/podcast/',                                                                                                                                        'rss',     'Technology & AI',             true, false, NOW()),
  ('1c5881e2ddef', 'Signals & Threads',       'https://feeds.simplecast.com/L9810DOa',                                                                                                                                              'rss',     'Technology & AI',             true, false, NOW()),
  ('136441bc78e0', 'Masters in Business',     'https://www.omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/4e4cd910-40a1-4619-a5f3-ae2b0012ffff/5873a3cb-298f-40bc-b71f-ae2b0013000d/podcast.rss',               'rss',     'Finance & Investing',         true, false, NOW()),
  ('e0ac943d055f', 'Big Technology Podcast',  'https://feeds.megaphone.fm/LI3617121267',                                                                                                                                            'rss',     'Technology & AI',             true, false, NOW()),
  ('b192a608829d', 'RenMac',                  'https://anchor.fm/s/10928cc60/podcast/rss',                                                                                                                                          'rss',     'Finance & Investing',         true, false, NOW()),
  ('5dd0e3daa0e9', 'BG2Pod',                  'https://anchor.fm/s/f06c2370/podcast/rss',                                                                                                                                           'rss',     'Business & Startups',        true, false, NOW()),
  ('50ec7aea7594', 'The McKinsey Podcast',    'https://www.omnycontent.com/d/playlist/708664bd-6843-4623-8066-aede00ce0c8a/3f6f52af-fba1-496d-b11b-af040139456a/bfe0b44a-082f-495a-952a-af0401394590/podcast.rss',               'rss',     'Leadership & Productivity',  true, false, NOW()),
  ('6f289de43178', 'In Good Company',         'https://feeds.acast.com/public/shows/in-good-company-with-nicolai-tangen',                                                                                                          'rss',     'Business & Startups',        true, false, NOW()),
  ('12bd86afaafe', 'The Knowledge Project',   'https://anchor.fm/s/f6891d6c/podcast/rss',                                                                                                                                          'rss',     'Leadership & Productivity',  true, false, NOW())
ON CONFLICT (id) DO NOTHING;
